### ISSUE TITLE
Having some trouble with dependencies

### ISSUE THREAD

**Issue by instabot42** [bitfinexcom/bfx-hf-backtest#2]
`npm install` is failing. I've seen the following problems while trying to get this working...

Package file expects bfx-hf-strategy version that does not exist. Had to change this to "^1.0.0-alpha.1"

There were some errors about `eslint-plugin-react` being required but not included. `npm install eslint-plugin-react` resolved this error. If it is needed it should be added to the package file.

I was also seeing some build errors and deprecated warnings.

The logs are below, though it may be related to this warning...
```
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```

What versions should be used?

The log of the install...

```
vagrant@homestead:~/me/honey/bfx-hf-backtest/dist$ npm install
npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
npm WARN deprecated bignumber.js@6.0.0: Custom ALPHABET bug fixed in v7.0.2
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer

> node-zopfli@2.0.2 install /home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@10.9.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@10.9.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-zopfli/build'
  CXX(target) Release/obj.target/zopfli/src/zopfli-binding.o
make: Entering directory '/home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-zopfli/build'
  CXX(target) Release/obj.target/zopfli/src/zopfli-binding.o
../src/zopfli-binding.cc: In member function ‘virtual void nodezopfli::CompressWorker::HandleOKCallback()’:
../src/zopfli-binding.cc:137:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/zopfli-binding.h:5:0,
                 from ../src/zopfli-binding.cc:3:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/zopfli-binding.cc: In member function ‘virtual void nodezopfli::CompressWorker::HandleOKCallback()’:
../src/zopfli-binding.cc:137:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/zopfli-binding.h:5:0,
                 from ../src/zopfli-binding.cc:3:
../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
  CXX(target) Release/obj.target/zopfli/src/png/zopflipng.o
sed: can't read ./Release/.deps/Release/obj.target/zopfli/src/zopfli-binding.o.d.raw: No such file or directory
rm: cannot remove './Release/.deps/Release/obj.target/zopfli/src/zopfli-binding.o.d.raw': No such file or directory
zopfli.target.mk:132: recipe for target 'Release/obj.target/zopfli/src/zopfli-binding.o' failed
make: *** [Release/obj.target/zopfli/src/zopfli-binding.o] Error 1
make: Leaving directory '/home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-zopfli/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Linux 4.15.0-22-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-zopfli/lib/binding/node-v64-linux-x64/zopfli.node" "--module_name=zopfli" "--module_path=/home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-zopfli/lib/binding/node-v64-linux-x64"
gyp ERR! cwd /home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-zopfli
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-zopfli/lib/binding/node-v64-linux-x64/zopfli.node --module_name=zopfli --module_path=/home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-zopfli/lib/binding/node-v64-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
node-pre-gyp ERR! System Linux 4.15.0-22-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-zopfli
node-pre-gyp ERR! node -v v10.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-zopfli/lib/binding/node-v64-linux-x64/zopfli.node --module_name=zopfli --module_path=/home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-zopfli/lib/binding/node-v64-linux-x64' (1)

> bfx-hf-indicators@1.0.1 postinstall /home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/bfx-hf-indicators
> npm run build


> bfx-hf-indicators@1.0.1 build /home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/bfx-hf-indicators
> babel -q ./index.js -d ./dist && babel -q ./lib -d ./dist/lib && copy package.json dist

You have mistakenly installed the `babel` package, which is a no-op in Babel 6.
Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package.

    npm uninstall -g babel
    npm install --save-dev babel-cli

See http://babeljs.io/docs/usage/cli/ for setup instructions.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bfx-hf-indicators@1.0.1 build: `babel -q ./index.js -d ./dist && babel -q ./lib -d ./dist/lib && copy package.json dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bfx-hf-indicators@1.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-10-27T10_35_40_831Z-debug.log
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/blocksplitter.o.1~postinstall: Failed to exec postinstall script
sh: 0: getcwd() failed: No such file or directorye bfx-hf-indicators@1.0.1~postinstall: Failed to exec postinstall script
sh: 0: getcwd() failed: No such file or directorye bfx-hf-indicators@1.0.1~postinstall: Failed to exec postinstall script
sh: 0: getcwd() failed: No such file or directory
sed: can't read ./Release/.deps/Release/obj.target/zopfli/zopfli/src/zopfli/blocksplitter.o.d.raw: No such file or directory
/bin/sh: 1: cannot create ./Release/.deps/Release/obj.target/zopfli/zopfli/src/zopfli/blocksplitter.o.d: Directory nonexistent
zopfli.target.mk:135: recipe for target 'Release/obj.target/zopfli/zopfli/src/zopfli/blocksplitter.o' failed
make: *** [Release/obj.target/zopfli/zopfli/src/zopfli/blocksplitter.o] Error 2
make: Leaving directory '/home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-zopfli/build'
 build error         ......] - postinstall: info lifecycle bfx-hf-indicators@1.0.1~postinstall: Failed to exec postinstall script
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Linux 4.15.0-22-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-zopfli/lib/binding/node-v64-linux-x64/zopfli.node" "--module_name=zopfli" "--module_path=/home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-zopfli/lib/binding/node-v64-linux-x64"
gyp ERR! cwd /home/vagrant/me/honey/bfx-hf-backtest/dist/node_modules/node-zopfli
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@2.0.2 (node_modules/node-zopfli):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@2.0.2 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bfx-hf-indicators@1.0.1 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bfx-hf-indicators@1.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by f3rno** [comment]
`eslint-plugin-react` is not required, and I don't see anything about it in your log output. I've updated the `bfx-hf-strategy` version that is referenced, an update for this repo will be published today.
