### ISSUE TITLE
Offline example fails: context is undefined

### ISSUE THREAD

**Issue by emorling** [bitfinexcom/bfx-hf-backtest#35]
#### Issue type
- [ x] bug
- [x ] missing functionality

#### Brief description & Steps to reproduce
Cloned the repository and fired up the offline example

` node examples/offline_bt.js`

This produces

```
(node:17633) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'once' of undefined
    at Object.execOffline (/Users/eliamorling/Documents/workspace/bfx-hf-backtest/lib/exec_offline.js:82:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async run (/Users/eliamorling/Documents/workspace/bfx-hf-backtest/examples/offline_bt.js:32:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17633) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17633) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
#### Additional notes

It seems like the context is required in exec_offline.js but that param is not sent. What should the context be for the example to run?

**Comment by maxhq** [comment]
There have been some breaking changes to the Bitfinex modules done by @tarcisiozf without updates to the documentation and - as it seems - without much attention to all use cases. This renders the open source backtest framework quite useless.
For days now I am trying to fix my private project to work again. I now have to use `HFBT.execOffline()` and pass it `PriceFeed` and `PerformanceManager` instances (from `bfx-hf-strategy-perf`) as well as `ExecutionContext`, `DataPointFeed` and `DataPointStream` instances (from `bfx-hf-data-server`). And still it does not work, seems to be stuck in an endless loop or some kind of polling... I am a bit frustrated.
